/**
 * @see https://stylelint.io/user-guide/configure/
 * @type {import('stylelint').Config}
 */
export default {
  ignoreFiles: [
    '**/node_modules/**',
    '**/dist/**',
    '**/build/**',
    '**/coverage/**',
    '**/*.log',
    '**/npm-debug.log*',
    '**/.git/**',
    '**/.idea/**',
    '**/.vscode/**',
    '**/.DS_Store',
  ],
  defaultSeverity: 'warning',
  extends: ['stylelint-config-standard-scss'],
  plugins: [
    'stylelint-scss',
    'stylelint-order',
  ],
  rules: {
    'font-family-name-quotes': 'always-unless-keyword',
    'color-hex-length': 'long',
    'color-function-alias-notation': null,
    'color-function-notation': null,
    'alpha-value-notation': null,
    'custom-property-empty-line-before': null,
    'custom-property-pattern': null,
    'selector-class-pattern': null,
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-order': [
      'content',
      'appearance',
      'order',
      'flex',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'grid-area',
      'grid-column',
      'grid-column-start',
      'grid-column-end',
      'grid-row',
      'grid-row-start',
      'grid-row-end',
      'align-self',
      'justify-self',

      'position',
      'z-index',
      'inset',
      'top',
      'right',
      'bottom',
      'left',

      'overflow',
      'overflow-x',
      'overflow-y',
      'overscroll-behavior',

      'display',
      'grid',
      'grid-template',
      'grid-template-rows',
      'grid-template-columns',
      'grid-template-areas',
      'grid-auto-columns',
      'grid-auto-rows',
      'grid-auto-flow',
      'flex-direction',
      'flex-wrap',
      'justify-content',
      'align-items',
      'align-content',
      'float',
      'clear',
      'column-count',
      'break-inside',
      'break-before',
      'break-after',
      'gap',
      'row-gap',
      'column-gap',

      // Размеры
      'box-sizing',
      'aspect-ratio',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',

      // Внешние отступы
      'margin',
      'margin-block',
      'margin-inline',
      'margin-top',
      'margin-bottom',
      'margin-left',
      'margin-right',

      // Внутренние отступы
      'padding',
      'padding-block',
      'padding-inline',
      'padding-top',
      'padding-bottom',
      'padding-left',
      'padding-right',

      // Шрифты
      'font',
      'font-family',
      'font-size',
      'font-weight',
      'font-style',
      'font-variant',
      'font-size-adjust',
      'font-stretch',
      'line-height',
      'letter-spacing',
      'white-space',
      'overflow-wrap',
      'hyphens',
      'text-align',
      'text-decoration',
      'text-transform',
      'text-indent',
      'text-overflow',
      'color',

      // Фон
      'background',
      'background-image',
      'background-position',
      'background-position-x',
      'background-position-y',
      'background-size',
      'background-repeat',
      'background-attachment',
      'background-origin',
      'background-clip',
      'background-color',
      'object-fit',

      // Границы
      'border',
      'border-block',
      'border-inline',
      'border-width',
      'border-style',
      'border-color',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-radius',

      'outline',
      'outline-color',
      'outline-style',
      'outline-width',
      'outline-offset',

      // Тень
      'box-shadow',
      'filter',

      // Списки
      'list-style',
      'list-style-position',
      'list-style-type',
      'list-style-image',
      'counter-set',
      'counter-reset',
      'counter-increment',

      // Таблицы
      'border-collapse',
      'border-spacing',
      'empty-cells',

      // Другие визуальные
      'visibility',
      'opacity',
      'cursor',
      'clip',
      'clip-path',
      'transition',
      'transition-behavior',
      'transition-delay',
      'transition-duration',
      'transition-property',
      'transition-timing-function',
      'transform-origin',
      'transform',
      'rotate',
      'scale',
      'translate',
      'animation',
      'animation-name',
      'animation-duration',
      'animation-timing-function',
      'animation-delay',
      'animation-iteration-count',
      'animation-direction',
      'animation-fill-mode',
      'animation-play-state',
      'animation-timeline',
      'animation-range',
      'animation-range-start',
      'animation-range-end',
      'resize',

      // Специальные
      'pointer-events',
      'user-select',

      // SVG
      'fill',
      'stroke',
      'stroke-width',
      'stroke-linecap',
      'stroke-dasharray',
      'stroke-dashoffset',
    ],
    'no-descending-specificity': null,
    'value-keyword-case': [
      'lower',
      {
        ignoreKeywords: ['currentColor'],
      },
    ],
    'no-empty-source': [true, { severity: 'warning' }],
    'scss/dollar-variable-pattern': null,
    'scss/dollar-variable-empty-line-before': null,
    'scss/operator-no-newline-before': null,
    'scss/operator-no-newline-after': null,
  },
}